### ISSUE TITLE
add minisign and age

### ISSUE THREAD

**Issue by parabirb** [ibraheemdev/modern-unix#1]
[minisign](https://github.com/jedisct1/minisign) and [age](https://github.com/FiloSottile/age) are modern, secure replacements for GPG. minisign can be used for signing and verifying files, while age can be used for encrypting files.

**Comment by ibraheemdev** [comment]
I kind of wanted this list to focus mainly on productivity tools, I don't want to make any security-related recommendations.

(Sorry for the late reply.)
