### ISSUE TITLE
Proposal: neovim

### ISSUE THREAD

**Issue by jcgutier** [ibraheemdev/modern-unix#104]
https://github.com/neovim/neovim

**Comment by William9923** [comment]
Hi, could you assign this for me? thx

**Comment by mfilenko** [comment]
Wondering why do you consider Neovim modern? :)

In the spirit of this project I think I'd be more expecting to see something like [Helix](https://helix-editor.com/) here instead

**Comment by NukeManDan** [comment]
Was coming here to propose the same (helix) on this list

**Comment by ibraheemdev** [comment]
Sorry, don't really want to get into text editors on this list :)
