### ISSUE TITLE
Integrate pjy as a jq alternative

### ISSUE THREAD

**Issue by hydrargyrum** [ibraheemdev/modern-unix#12]
[pjy](https://github.com/hydrargyrum/pjy) is a similar tool to `jq` but uses a less abstruse syntax, as it proposes a familiar-to-many-people python syntax (with optional syntactic sugar), making it much simpler to learn and use. Disclaimer: I'm the pjy author.

**Comment by ibraheemdev** [comment]
I wanted this list to be curated of well-established tools, avoiding duplicates, even if they are slightly different. You can try submitting your tool to https://github.com/alebcay/awesome-shell. Thanks.
