### ISSUE TITLE
Proposal: Helix

### ISSUE THREAD

**Issue by nuke-web3** [ibraheemdev/modern-unix#121]
(based on https://github.com/ibraheemdev/modern-unix/issues/104#issuecomment-1580945634) 

https://github.com/helix-editor/helix

**Comment by TheTedAdams** [comment]
Duplicate of #35 ?

**Comment by NukeManDan** [comment]
Kinda - this isn't a _replacement_ for `vim` but an _alternative_ in the same "family". So I think the proposal isn't quite a dup.

**Comment by ibraheemdev** [comment]
Sorry, don't really want to get into text editors on this list :)
