### ISSUE TITLE
Proposal: Eza

### ISSUE THREAD

**Issue by infectormp** [ibraheemdev/modern-unix#125]
https://github.com/eza-community/eza

eza is a modern, maintained replacement for the venerable file-listing command-line program ls that ships with Unix and Linux operating systems, giving it more features and better defaults.

**Comment by jubalh** [comment]
Just yesterday opened: https://github.com/ibraheemdev/modern-unix/pull/124 ...

**Comment by fhoekstra** [comment]
Just read that [exa is unmaintained](https://github.com/ogham/exa/issues/1243) since a few months, so this issue is more than just a proposal now, we might classify it as a bug. We should not be directing people towards and unmaintained tool when there is an actively maintained fork.
