### ISSUE TITLE
What are your thought on adding xplr:A hackable, minimal, fast TUI file explorer

### ISSUE THREAD

**Issue by KAGEYAM4** [ibraheemdev/modern-unix#126]
https://github.com/sayanarijit/xplr

**Comment by slavaGanzin** [comment]
Typical rust project - a lot of complex features, but in a same time lacks most obvious ones. Like file preview. Definitely not unix-way: does a lot of stuff and doesn't do any of it well.

**Comment by KAGEYAM4** [comment]
> Typical rust project - a lot of complex features, but in the a same time lacks most obvious ones: file preview, file copy, etc. Definitely not unix-way: does a lot of stuff and doesn't do any of it well.

can you recommend some alternative to this , which one do you use ?

**Comment by slavaGanzin** [comment]
@KAGEYAM4 
[ranger](https://github.com/ranger/ranger#features)

**Comment by jubalh** [comment]
> can you recommend some alternative to this , which one do you use ?

https://github.com/vifm/vifm
