### ISSUE TITLE
Proposal: tailspin

### ISSUE THREAD

**Issue by infectormp** [ibraheemdev/modern-unix#130]
not a replacement for tail, but might be useful

https://github.com/bensadeh/tailspin
A log file highlighter

**Comment by StewAlexander-com** [comment]
Hmm I prefer [chromaterm](https://github.com/hSaria/ChromaTerm), since it works even over ssh or can be called locally with the "ct" operand -- how is the above better?

**Comment by ccoVeille** [comment]
I would say with a touch of humor that  `tailspin` is maintained by @bensadeh while `chromaterm` project is archived 😁

I agree with the suggestion of adding tailspin to the repository.

**Comment by johnalanwoods** [comment]
feel free to PR over here: https://github.com/johnalanwoods/maintained-modern-unix

**Comment by ccoVeille** [comment]
> feel free to PR over here: https://github.com/johnalanwoods/maintained-modern-unix

Oh indeed. I'm following you, haha. I have just seen this old thread in my github notification

**Comment by ibraheemdev** [comment]
This isn't really the type of tool I am looking for. I realize there aren't clear contribution guidelines at this point, sorry!
