### ISSUE TITLE
George Bentham 10

### ISSUE THREAD

**Issue by Benteth** [ibraheemdev/modern-unix#135]
George Bentham 10

_Originally posted by @chapmanjacobd in https://github.com/ibraheemdev/modern-unix/issues/134#issuecomment-1880106762_

**Comment by chapmanjacobd** [comment]
well.... if we're doing spams I recommend this podcast: 

[Harry Potter and the Methods of Rationality](https://hpmorpodcast.com/?page_id=56)

**Comment by Benteth** [comment]
> well.... if we're doing spams I recommend this podcast: 
> 
> 
> 
> [Harry Potter and the Methods of Rationality](https://hpmorpodcast.com/?page_id=56)
