### ISSUE TITLE
Remove ag; rg is better

### ISSUE THREAD

**Issue by esafak** [ibraheemdev/modern-unix#62]
You don't need to advertise ag; rg is better. If not remove them at least combine the entries.

https://blog.burntsushi.net/ripgrep/
https://www.reddit.com/r/vim/comments/f9gqe4/rigrep_or_ag/
https://news.ycombinator.com/item?id=12567328
https://beyondgrep.com/feature-comparison/

**Comment by kseistrup** [comment]
Also:

* `ag` doesn't seem to be maintained: last commit was August 2018.
* `ag` cannot reliebaly be used to search in UTF-8 documents
