### ISSUE TITLE
Add z

### ISSUE THREAD

**Issue by Nezteb** [ibraheemdev/modern-unix#7]
https://github.com/rupa/z

I use `z` daily in conjunction with `fzf` and it's a magical combo.

**Comment by ibraheemdev** [comment]
The list already has [zoxide](https://github.com/ajeetdsouza/zoxide) which is a cross platform tool based on z with fzf integration.

**Comment by Nezteb** [comment]
Oh! I didn't see `z` mentioned anywhere, but see now in the `zoxide` gif that it mentions `z`. `fzf` is listed separately so I figured `z` would be a good candidate.

Perhaps `zoxide`'s description could mention that: "a cross platform tool based on `z` with `fzf` integration"?

**Comment by ibraheemdev** [comment]
I added "inspired by `z`" to the description, most of these tools are cross platform anyways, and `fzf` integrates with pretty much anything :smile:
