### ISSUE TITLE
Proposal: remv

### ISSUE THREAD

**Issue by dertuxmalwieder** [ibraheemdev/modern-unix#81]
[dertuxmalwieder/remv](https://github.com/dertuxmalwieder/remv) is an alternative to `mv` that does recursive renaming with regular expressions (`remv` = `regex move`) and a preview mode.

**Comment by slavaGanzin** [comment]
This is standard Unix belt:
https://man7.org/linux/man-pages/man1/rename.1.html

Are there any features in renv you cannot do with rename?

**Comment by dertuxmalwieder** [comment]
From the man page:

> The rename command is part of the util-linux package

So:
- It is preferably a Linux application. Yet, this repository is “modern Unix”, not “modern Linux”.
- It would require a whole suite of applications and libraries, not only one executable.
