### ISSUE TITLE
prepare ubuntu meta-package to install all of those tools

### ISSUE THREAD

**Issue by abecadel** [ibraheemdev/modern-unix#85]
It would be useful for ubuntu users to be able to just type in
`sudo apt install modern-unix`
and have all of the tools installed

**Comment by PacMicro** [comment]
> ubuntu 用户只需输入 `sudo apt install modern-unix` 并安装所有工具会很有用

Among these alternatives, some are redundant, such as exa and lsd, users should choose to install freely instead of packaging it for you at one time
